export const LOGIN_WITH_EMAIL_ACTION_TYPES = {
    LOGIN_WITH_EMAIL_REQUEST: "LOGIN_WITH_EMAIL_REQUEST",
    LOGIN_WITH_EMAIL_FULFILLED: "LOGIN_WITH_EMAIL_FULFILLED",
    LOGIN_WITH_EMAIL_REJECTED: "LOGIN_WITH_EMAIL_REJECTED"
};

export const FORGOT_PASSWORD_ACTION_TYPES = {
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_FULFILLED: "FORGOT_PASSWORD_FULFILLED",
    FORGOT_PASSWORD_REJECTED: "FORGOT_PASSWORD_REJECTED"
};

export const CREATE_ACCOUNT_ACTION_TYPES = {
    CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
    CREATE_ACCOUNT_FULFILLED: "CREATE_ACCOUNT_FULFILLED",
    CREATE_ACCOUNT_REJECTED: "CREATE_ACCOUNT_REJECTED"
};

export const CREATE_BANK_ACCOUNT_ACTION_TYPES = {
    CREATE_BANK_ACCOUNT_REQUEST: "CREATE_BANK_ACCOUNT_REQUEST",
    CREATE_BANK_ACCOUNT_FULFILLED: "CREATE_BANK_ACCOUNT_FULFILLED",
    CREATE_BANK_ACCOUNT_REJECTED: "CREATE_BANK_ACCOUNT__REJECTED"
};

export const FETCH_BANK_ACCOUNT_ACTION_TYPES = {
    FETCH_BANK_ACCOUNT_REQUEST: "FETCH_BANK_ACCOUNT_REQUEST",
    FETCH_BANK_ACCOUNT_FULFILLED: "FETCH_BANK_ACCOUNT_FULFILLED",
    FETCH_BANK_ACCOUNT_REJECTED: "FETCH_BANK_ACCOUNT__REJECTED"
};

export const ADD_POLL_ACTION_TYPES = {
    ADD_POLL_REQUEST: "ADD_POLL_REQUEST",
    ADD_POLL_FUFILLED: "ADD_POLL_FUFILLED",
    ADD_POLL_REJECTED: "ADD_POLL_REJECTED"
}

export const ADD_CANDIDATE_ACTION_TYPES = {
    ADD_CANDIDATE_REQUEST: "ADD_CANDIDATE_REQUEST",
    ADD_CANDIDATE_FUFILLED: "ADD_CANDIDATE_FUFILLED",
    ADD_CANDIDATE_REJECTED: "ADD_CANDIDATE_REJECTED"
}

export const GET_CANDIDATES_ACTION_TYPES = {
    GET_CANDIDATES_REQUEST: "GET_CANDIDATES_REQUEST",
    GET_CANDIDATES_FUFILLED: "GET_CANDIDATES_FUFILLED",
    GET_CANDIDATES_REJECTED: "GET_CANDIDATES_REJECTED"
}

export const GET_MY_POLL_ACTION_TYPES = {
    GET_MY_POLL_REQUEST: "GET_MY_POLL_REQUEST",
    GET_MY_POLL_FUFILLED: "GET_MY_POLL_FUFILLED",
    GET_MY_POLL_REJECTED: "GET_MY_POLL_REJECTED"
}

export const GET_POLLS_ACTION_TYPES = {
    GET_POLLS_REQUEST: "GET_POLLS_REQUEST",
    GET_POLLS_FUFILLED: "GET_POLLS_FUFILLED",
    GET_POLLS_REJECTED: "GET_POLLS_REJECTED"
}

export const ADD_VOTE_ACTION_TYPES = {
    ADD_VOTE_REQUEST: "ADD_VOTE_REQUEST",
    ADD_VOTE_FUFILLED: "ADD_VOTE_FUFILLED",
    ADD_VOTE_REJECTED: "ADD_VOTE_REJECTED"
}

export const GET_A_CANDIDATE_ACTION_TYPES = {
    GET_A_CANDIDATE_REQUEST: "GET_A_CANDIDATE_REQUEST",
    GET_A_CANDIDATE_FUFILLED: "GET_A_CANDIDATE_FUFILLED",
    GET_A_CANDIDATE_REJECTED: "GET_A_CANDIDATE_REJECTED"
}

export const GET_POLL_VOTES_ACTION_TYPES = {
    GET_POLL_VOTES_REQUEST: "GET_POLL_VOTES_REQUEST",
    GET_POLL_VOTES_FUFILLED: "GET_POLL_VOTES_FUFILLED",
    GET_POLL_VOTES_REJECTED: "GET_POLL_VOTES_REJECTED"
}

export const DELETE_POLL_ACTION_TYPES = {
    DELETE_POLL_REQUEST: "DELETE_POLL_REQUEST",
    DELETE_POLL_FUFILLED: "DELETE_POLL_FUFILLED",
    DELETE_POLL_REJECTED: "DELETE_POLL_REJECTED"
}